# Generated by Django 5.1.6 on 2025-03-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='registration_source',
            field=models.CharField(default='website', max_length=20),
        ),
    ]
